### ISSUE TITLE
User in 'users_admins' are not added to 'admins' group

### ISSUE THREAD

**Issue by ganto** [debops/ansible-users#14]
I'm trying to use the ansible-users module to setup some local user accounts. Still I have some trouble to understand the configuration.

    users_ganto:
      - name: 'ganto'
        
    users_admins:
      - users_ganto

I defined a user (in `group_vars/all/users.yml`) and added it to the `users_admins`. My expectation was that it is automatically added to the `admins` POSIX group, which wasn't the case.

    debops@admin01:~$ id ganto
    uid=1000(ganto) gid=1000(ganto) groups=1000(ganto)

Also I'm no clear what is the scope of these different user lists. Even I didn't add the user to the `users_list`, the user was still created on the machine.

Is there the code not yet fully ready or did I completely misunderstood these configuration values?

Cheers, ganto

**Comment by drybjed** [comment]
First, some background on inventory: Ansible inventory has basically three levels:

- all hosts - `inventory/group_vars/all/`
- hosts in a group - `inventory/group_vars/group_of_hosts/`
- specific hosts - `inventory/host_vars/hostname/`

You can put variables on any "level" you want, and more specific levels will override the less specific ones, basically `all` < `group` < `host`.

With `debops.users` you can create any arrangement of users on hosts using `users_*_list`, specifically:

- users that should be on all hosts should be put in `users_list` variable, which should go into `inventory/group_vars/all/`;
- users that should be on hosts in specific groups only, should go into `users_group_list`, which should go into `inventory/group_vars/group_of_hosts/` - but only one "level" of that is supported, so choose wiesely;
- users that should only be created in a specific host, should go into `users_host_list` which should be defined in `inventory/host_vars/hostname/`;

Otherwise, all of the `users_*_list` variables are the same.

Also, `users_admins` list is the same, ie. name does not imply that these accounts should belong to `admins` system group; it's there just for your convenience to group some accounts together. Maybe you want different admins for different groups of hosts? Here's a way to do it - put different list of accounts in `users_admins` in different host groups and Ansible will correctly split them among hosts.

To actually add the account to `admins` group, you need to define it like this:

```
users_list:
  - name: 'username'
    groups: [ 'admins' ]
```

I hope that clears things up.

**Comment by ganto** [comment]
Thanks a lot for this explanation. Sorry, I'm quite new to Ansible so I can yet fully see through the technical dependencies behind this. I'm a bit puzzled about the scope dependency of these variables. It's not really intuitive without further explanation that certain variables make only sense in a specific level.

Does this mean that the grouping variables (`users_*_list`/`users_admins`/`users_list`) in the configuration has actually nothing to do with the action of defining and creating the users, but only for using the variables for further configuration in other roles? Or what is a use case where I want to group users? If I understand correctly I cannot easily assign e.g. the group `admins` to all users in the `users_admins` group, right?

**Comment by drybjed** [comment]
@ganto Variables in Ansible are in 1 flat namespace, basically available anywhere within the playbooks and roles at all times. But within inventory, Ansible treats them a little differently - if you have say, `users_list` variable and you specify it in `inventory/group_vars/all.yml` file, and then you have the same `users_list` variable specified in `inventory/host_vars/hostname.yml`, the one from the `host_vars/` will take precedence, by "masking" the one from `group_vars/`. To avoid this, I use 3 different variables for different inventory levels and Ansible combines them together into one list.

`users_*_list` variables, `users_admins` hold the data that `debops.users` role uses to create user accounts. If you don't care about different inventory levels, etc, just stick to using `users_list`, and it will be easy.

Right now there's no way defined to add multiple users to a group at once, in `debops.users`. You need to define user accounts first. This is to avoid an issue when you add a list of users to a group, but some accounts don't exist.

**Comment by ganto** [comment]
I think, I found a nice way to do what I wanted, thanks to https://github.com/debops/ansible-auth. I would just add the `users_admins` to the `auth_admin_accounts` in `inventory/group_vars/all/auth.yml`:

    auth_admin_accounts: "[ '{{ ansible_ssh_user }}' ] + users_admins"
