### ISSUE TITLE
lookup error with 'task_src' when using debops.ansible-users without having the debops plugins

### ISSUE THREAD

**Issue by aks** [debops/ansible-users#25]
It appears that it is no longer possible to use `debops.ansible-users` as an independent playbook now that there is a `lookup('task_src', ...)` invocation in the `tasks/main.yml` file.

Perhaps you can explain how to get the debops utility plugins installed so that the dependent playbooks, like ansible-users can still work?

**Comment by drybjed** [comment]
Required [lookup plugins](https://github.com/debops/debops-playbooks/tree/master/playbooks/lookup_plugins) and others can be found in main playbook (debops/debops-playbooks). You can just drop them where your playbook is and it should work.

**Comment by aks** [comment]
Thanks for the prompt reply.

So, here is my perspective.

I've been using `debops.ansible-users` for months, and suddenly, after doing a recursive pull on the repo, which also pulled the latest changes in the `debops.ansible-users` repo, I get these fun, new `lookup` errors.

This change is not backward compatible, and there is no explanation of this new dependency, or how to resolve it.  In fact, I had to do a search on `"task_src"` just to figure out what was going on.

Thanks
Alan

**Comment by drybjed** [comment]
@aks DebOps documentation is still lacking, I know. But I'm working on it; recently playbook-wide docs have been moved to `debops-playbooks` repository and are now available in http://docs.debops.org/. Relevant section (to be definitely expanded) about those custom plugins:

http://docs.debops.org/en/latest/debops-playbooks/docs/custom-features.html#file-template-and-task-hooks

**Comment by aks** [comment]
I appreciate the work being put into the debops library of playbooks, as well as the sharing.  
I also know how hard it is to limit unnecessary dependencies.

**Comment by max-b** [comment]
I wonder if the modular elements of the debops-playbooks could be separated into their own galaxy roles in the same way that debops.secret is? That way we could keep any plugins within a version control framework where changes on your end can be updated on ours?

**Comment by dalyc** [comment]
I'm having this issue with debops.auth - I only started using ansible today so please don't assume any knowledge on my part. There ansible.cfg in my project directory has the following 
```lookup_plugins = <mydir>/ansible/lookup_plugins:<myhome>/.local/share/debops/debops-playbooks/playbooks/lookup_plugins:/usr/share/ansible/lookup_plugins
```

<myhome>/.local/share/debops/debops-playbooks/playbooks/lookup_plugins has these files
file_src.py,  lists.py,  task_src.py,  task_src.pyc,  template_src.py

I'm not sure what is meant by "just drop them where your playbook is" but i tried copying the lookup_plugins directory that has the files to <mydir>/ansible/playbooks but it didn't work - i still get

```TASK [debops.auth : debops.auth : DebOps pre_tasks hook] ************************
fatal: [test]: FAILED! => {
    "failed": true, 
    "msg": "ERROR! lookup plugin (task_src) not found"
}```

**Comment by drybjed** [comment]
Ansible looks for its plugins in the `*_plugins/` directories relative to the playbook, so you should put them in `/ansible/playbooks/lookup_plugins/` instead. Try it and report back if it works.

**Comment by dalyc** [comment]
That's what I did do - here is the dir structure of my test project.

```~/debops-test % find .
.
./.gitignore
./.debops.cfg
./ansible
./ansible/playbooks
./ansible/playbooks/lookup_plugins
./ansible/playbooks/lookup_plugins/task_src.py
./ansible/playbooks/lookup_plugins/task_src.pyc
./ansible/playbooks/lookup_plugins/template_src.py
./ansible/playbooks/lookup_plugins/lists.py
./ansible/playbooks/lookup_plugins/file_src.py
./ansible/roles
./ansible/inventory
./ansible/inventory/hosts
./ansible/inventory/host_vars
./ansible/inventory/group_vars
./ansible/inventory/group_vars/all
./ansible.cfg```

The above was created with 
```debops-init debops-test
cd debops-test
cp -a ~/.local/share/debops/debops-playbooks/playbooks/lookup_plugins ansible/playbooks```

The only other thing I've done is add my remote vm to the hosts file (under ansible-controllers) and run the debops command i.e I haven't  added any custom playbook - I just wanted to see the basic debian install on my test vm.

I have retried again with only those steps to make sure I changed nothing else but i get the same results. Here is my ansible --version output in case it helps

```hippo~/debops-test % ansible --version
ansible 2.0.0 (devel f2fcc39513) last updated 2015/07/22 08:58:38 (GMT +1100)
  lib/ansible/modules/core: (detached HEAD 55bc9e8fb1) last updated 2015/07/22 08:58:51 (GMT +1100)
  lib/ansible/modules/extras: (detached HEAD 26c1bd76c3) last updated 2015/07/22 08:58:51 (GMT +1100)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/07/21 19:37:22 (GMT +1100)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/07/21 19:37:30 (GMT +1100)
  configured module search path = /home/colin/debops-test/ansible/library:/home/colin/.local/share/debops/debops-playbooks/playbooks/library:/usr/share/ansible/library```

**Comment by drybjed** [comment]
At the moment DebOps is not compatible with Ansible v2, which is missing support for old custom plugins, and has other bugs. Switch to Ansible `1.9-stable` branch, it should work fine.

**Comment by dalyc** [comment]
Ok thanks - that got me a little further. But now it dies on this - I can open a separate ticket for this if you prefer...

<pre>
TASK: [Read the host UUID] **************************************************** 
failed: [test] => {"changed": false, "failed": true}
msg: this module requires key=value arguments (['dmidecode', '--string', 'system-uuid', '|', 'tail', '-n', '1', '||', 'true', '#USE_SHELL'])
</pre>

**Comment by drybjed** [comment]
What...? This is a `shell` module. Something must be wrong... Could you come to `#debops` IRC channel on FreeNode so we could discuss it in real time?

**Comment by xbeta** [comment]
@drybjed you are telling people to "drop them" into library, that doesn't sound very much VCS friendly. 
It looks like debops is somewhat bloated in design.

**Comment by drybjed** [comment]
@xbeta I agree, it's bloated, want to know why?

Imagine that you are setting up some Ansible playbooks and roles for your environment. You wouldn't create something like `debops.users`, because it doesn't make sense when you can just do:
```
---
- hosts: all
  sudo: True
  tasks:
    - user:
        name: '{{ item }}'
        state: 'present'
      with_items: [ 'alice', 'bob', 'justin' ]
```
This is basically all it takes to setup some user accounts. Of course there would be additional parameters like password, GECOS, you would probably go with dict user definition in a list instead. Perhaps you would clone some dotfiles for each one. The point is, when you create Ansible playbooks and roles only for yourself, they don't need to be complicated, bloated, etc.

And when you want or need to change something? No problem, just add another task to your playbook, or another role. You can do whatever you like with them, they are your playbooks.

This all changes when you want to share your playbooks and roles either publicly, or privately with someone else. Suddenly, problems arise. You cannot change your playbooks willy-nilly because it will affect everyone that uses them. If someone needs some custom tasks added before creating users, sure, they can add them to the playbook but they lose the ability to get upgrades from your repository. Either they will maintain their own fork of the playbook/role, or they need to painfully manage all the changes in your git repository.

So how to fix that problem, in a way that is general enough that can be applied to any role for convenience, and requires least amount of changes from the users of your playbook that don't need to use it because defaults are enough for them? Traditionally this is done using some kind of "hooks" which programs access to see if there are any customizations by the user and run them if needed.

What hooks would we need to handle issues with custom playbook modifications? We need a hook that allows you to inject tasks to a playbook/role without modifying it. A hook to replace a file or template with your own version would also be nice, so that you are not forced to use templates/files that come with the role, but you can still update that role in the future.

Unfortunately at the moment Ansible doesn't have these kind of hooks built in. Perhaps they could be added in time Ansible v2 comes around, but I hadn't heard anything. Maybe @bcoca or @abadger could chime in and add something like this in the future.

In the meantime, on `#debops` IRC channel we came up, and @rchady coded, a crutch, which are `task_src`, `file_src` and `template_src` lookup plugins, which use DebOps configuration file to pull data from external repositories. Basically, `task_src` allows you to inject custom task files in specified places via `include` module, and `file_src` / `template_src` return a path to a file in specified directories on the filesystem if it's found, otherwise they return the path you specified in the query which points to file / template in the role.

If you use playbook from `debops-playbooks` repository as a base, it's all transparent. You don't need to do anything for these lookup plugins to work correctly, they don't even need a configuration present, it all just works.

But if you use DebOps roles separately, you need to provide Ansible with some additional code, ie. above plugins, for the role to work correctly. Otherwise Ansible will stop and complain that some plugins that are specified in the role are missing, which is perfectly OK on the Ansible's part. This is essentially the least amount of work user needs to do to make hooks working, that I mentioned above.

Could that be handled better? Probably, if it was done in Ansible core, so that all users could use this functionality. Perhaps above lookup plugins could be included in default Ansible plugins after some modifications to allow specifying a directory where lookup plugin looks for files. Maybe it's time to try and modify them to work that way and push them to Ansible proper, so that everyone could benefit from these "hooks" if they want to. We will see.

**Comment by jmatsushita** [comment]
Just bumped into this problem. Maybe to make it easier for those (like me) trying out debops roles without the whole debops scaffolding to allow cloning the plugin repos independently? Meaning instead of:
 - clone debops-playbook somewhere
 - copy lookup_plugins
 - (repeat when a new version is out)

Make it:
 - go to playbook directory
 - clone lookup_plugins
 - (just pull to update)

This would help tracking lookup_plugins releases with tags as well.

**Comment by drybjed** [comment]
@jmatsushita Sure, I suppose moving various DebOps-related plugins to a separate repository could be an option. The `debops` script that generates `ansible.cfg` could be changed to add plugin directories outside of `debops-playbooks/playbooks/` directory to Ansible variables so that plugins could be distributed completely independently of the playbooks themselves.
